name: Build Corne Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona o repositório do seu projeto
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instala dependências do QMK e Python
      - name: Setup QMK build environment
        run: |
          sudo apt update
          sudo apt install -y dfu-util gcc-avr avr-libc gcc-arm-none-eabi python3-pip git
          
          # Instala QMK CLI diretamente do repositório oficial
          python3 -m pip install --user git+https://github.com/qmk/qmk_cli.git
          
          # Adiciona o binário do usuário ao PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          # Clona o QMK Firmware com submódulos (resolve erro do LUFA)
          git clone --branch master --recurse-submodules https://github.com/qmk/qmk_firmware.git

      # 3️⃣ Copia os arquivos do seu keymap
      - name: Copy your keymap
        run: |
          mkdir -p qmk_firmware/keyboards/crkbd/rev1/keymaps/pedrohsb
          cp -r $GITHUB_WORKSPACE/* qmk_firmware/keyboards/crkbd/rev1/keymaps/pedrohsb/

      # 4️⃣ Compila o firmware
      - name: Build firmware
        run: |
          cd qmk_firmware
          qmk compile -kb crkbd/rev1 -km pedrohsb

      # 5️⃣ Faz upload do firmware compilado
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: corne-firmware
          path: qmk_firmware/crkbd_rev1_pedrohsb.hex
