name: Build Corne Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dfu-util gcc-avr avr-libc gcc-arm-none-eabi git

      - name: Clone QMK firmware
        run: |
          git clone --branch master https://github.com/qmk/qmk_firmware.git qmk_firmware
          cd qmk_firmware
          util/qmk_install.sh

      - name: Copy your keymap
        run: |
          mkdir -p qmk_firmware/keyboards/crkbd/rev1/keymaps/pedrohsb
          cp -r $GITHUB_WORKSPACE/* qmk_firmware/keyboards/crkbd/rev1/keymaps/pedrohsb/


      - name: Build firmware
        run: |
          cd qmk_firmware
          qmk compile -kb crkbd/rev1 -km pedrohsb

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: corne-firmware
          path: qmk_firmware/crkbd_rev1_pedrohsb.hex
